version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - log-net

  producer:
    build: ./producer
    container_name: producer-container
    depends_on:
      - mongo
    networks:
      - log-net

  consumer:
    build: ./consumer
    container_name: consumer-container
    depends_on:
      - mongo
    networks:
      - log-net

volumes:
  mongo-data:

networks:
  log-net:
    driver: bridge
